const LAT=38.3633556,LON=-97.6833972;const $=id=>document.getElementById(id);let charts=[],rows=[],frozenHour=null,deferredPrompt=null;
const apiUrl=()=>{const p=new URLSearchParams({latitude:LAT,longitude:LON,timezone:'America/Chicago',temperature_unit:'fahrenheit',wind_speed_unit:'mph',current:'temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,wind_gusts_10m',hourly:'temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m',past_hours:'48',forecast_hours:'1'});return`https://api.open-meteo.com/v1/forecast?${p}`};
const alertUrl=()=>`https://api.weather.gov/alerts/active?point=${LAT},${LON}`;
const round=(n,d=0)=>n==null||Number.isNaN(Number(n))?null:Number(Number(n).toFixed(d));
function wetBulbF(tF,rh){if(tF==null||rh==null)return null;const c=(tF-32)*5/9;const w=c*Math.atan(.151977*Math.sqrt(rh+8.313659))+Math.atan(c+rh)-Math.atan(rh-1.676331)+.00391838*Math.pow(rh,1.5)*Math.atan(.023101*rh)-4.686035;return w*9/5+32}
function dewPointF(tF,rh){if(tF==null||rh==null)return null;const c=(tF-32)*5/9,a=17.62,b=243.12,g=a*c/(b+c)+Math.log(rh/100),d=b*g/(a-g);return d*9/5+32}
function cardinal(d){if(d==null)return'—';return['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'][Math.round(d/22.5)%16]}
function parseLocal(s){return new Date(`${s}:00`)}function hourKey(d=new Date()){const x=new Date(d);x.setMinutes(0,0,0);return x.toISOString()}
async function json(url,headers={}){const r=await fetch(url,{cache:'no-store',headers});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function status(ok,text){$('statusDot').classList.toggle('bad',!ok);$('statusText').textContent=text}
function showToast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function currentTiles(c){const t=c.temperature_2m,rh=c.relative_humidity_2m,p=c.pressure_msl,w=c.wind_speed_10m,g=c.wind_gusts_10m,d=c.wind_direction_10m;$('dryBulb').textContent=t==null?'—':`${round(t)}°F`;$('wetBulb').textContent=t==null||rh==null?'—':`${round(wetBulbF(t,rh))}°F`;$('humidity').textContent=rh==null?'—':`${round(rh)}%`;$('dewPoint').textContent=t==null||rh==null?'—':`Dew point ${round(dewPointF(t,rh))}°F`;$('pressure').textContent=p==null?'—':`${round(p*.029529983,2)} inHg`;$('windSpeed').textContent=w==null?'—':`${round(w)} mph`;$('windGust').textContent=g==null?'—':`Gust ${round(g)} mph`;$('windDirection').textContent=cardinal(d);$('windDegrees').textContent=d==null?'—':`${round(d)}°`;$('windArrow').style.transform=`rotate(${d??0}deg)`;$('updatedText').textContent=`Updated ${new Date().toLocaleString()}`}
function chart(id,label,data){return new Chart($(id),{type:'line',data:{labels:label,datasets:[{data,borderWidth:2,tension:.25,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#9eb0c9',maxTicksLimit:8},grid:{color:'rgba(255,255,255,.06)'}},y:{ticks:{color:'#9eb0c9'},grid:{color:'rgba(255,255,255,.06)'}}}}})}
function rebuild(hourly){const times=(hourly.time||[]).map(parseLocal),now=new Date();now.setMinutes(0,0,0);rows=[];for(let i=23;i>=0;i--){const target=new Date(now);target.setHours(now.getHours()-i);const idx=times.findIndex(x=>x.getTime()===target.getTime());const t=idx<0?null:hourly.temperature_2m[idx],rh=idx<0?null:hourly.relative_humidity_2m[idx];rows.push({time:target,t,rh,wet:wetBulbF(t,rh),p:idx<0?null:hourly.pressure_msl[idx],w:idx<0?null:hourly.wind_speed_10m[idx]})}charts.forEach(c=>c.destroy());const labels=rows.map(r=>r.time.toLocaleTimeString([],{hour:'numeric'}));charts=[chart('tempChart',labels,rows.map(r=>round(r.t,1))),chart('humidityChart',labels,rows.map(r=>round(r.rh))),chart('pressureChart',labels,rows.map(r=>r.p==null?null:round(r.p*.029529983,2))),chart('windChart',labels,rows.map(r=>round(r.w,1)))];frozenHour=hourKey()}
async function weather(force=false){status(true,'Loading…');try{const d=await json(apiUrl());currentTiles(d.current||{});if(force||!rows.length||frozenHour!==hourKey())rebuild(d.hourly||{});status(true,'Live')}catch(e){console.error(e);status(false,'Data unavailable')}}
async function alerts(){try{const d=await json(alertUrl(),{Accept:'application/geo+json'}),f=d.features||[];if(!f.length){$('alertBanner').classList.add('hidden');return}const p=f[0].properties||{};$('alertTitle').textContent=p.event||'Weather Alert';$('alertText').textContent=p.headline||p.description||'';$('alertBanner').classList.remove('hidden')}catch(e){console.warn('Alert lookup failed',e)}}
function renderTable(){$('rollingBody').innerHTML=rows.map(r=>`<tr><td>${r.time.toLocaleString()}</td><td>${r.t==null?'—':round(r.t)+'°F'}</td><td>${r.wet==null?'—':round(r.wet)+'°F'}</td><td>${r.rh==null?'—':round(r.rh)+'%'}</td></tr>`).join('')}
async function copyRows(){const text=['Timestamp\tDry Bulb\tWet Bulb\tHumidity',...rows.map(r=>`${r.time.toLocaleString()}\t${r.t==null?'':round(r.t)}\t${r.wet==null?'':round(r.wet)}\t${r.rh==null?'':round(r.rh)}`)].join('\n');await navigator.clipboard.writeText(text);showToast('Copied for Excel')}
$('refreshBtn').onclick=()=>Promise.all([weather(true),alerts()]);$('rollingBtn').onclick=()=>{renderTable();$('modal').classList.remove('hidden')};$('closeBtn').onclick=()=>$('modal').classList.add('hidden');$('copyBtn').onclick=()=>copyRows().catch(()=>showToast('Clipboard access was blocked'));$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js'));
Promise.all([weather(true),alerts()]);setInterval(()=>Promise.all([weather(false),alerts()]),5*60*1000);setInterval(()=>{if(frozenHour!==hourKey())weather(true)},60*1000);
