const LAT=38.3633556,LON=-97.6833972,REFRESH_MS=5*60*1000;
const $=id=>document.getElementById(id);let charts=[],rows=[],frozenHour=null,deferredPrompt=null,lastUpdated=null,nextRefresh=null,forecastChart=null,lastWeather=null,lastAlerts=[];
const apiUrl=()=>{const p=new URLSearchParams({latitude:LAT,longitude:LON,timezone:'America/Chicago',temperature_unit:'fahrenheit',wind_speed_unit:'mph',precipitation_unit:'inch',current:'temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,wind_gusts_10m',hourly:'temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation',daily:'temperature_2m_max,temperature_2m_min,precipitation_sum,wind_gusts_10m_max,sunrise,sunset,weather_code',past_days:'2',forecast_days:'7'});return`https://api.open-meteo.com/v1/forecast?${p}`};
const alertUrl=()=>`https://api.weather.gov/alerts/active?point=${LAT},${LON}`;
const round=(n,d=0)=>n==null||Number.isNaN(Number(n))?null:Number(Number(n).toFixed(d));
function wetBulbF(tF,rh){if(tF==null||rh==null)return null;const c=(tF-32)*5/9;const w=c*Math.atan(.151977*Math.sqrt(rh+8.313659))+Math.atan(c+rh)-Math.atan(rh-1.676331)+.00391838*Math.pow(rh,1.5)*Math.atan(.023101*rh)-4.686035;return w*9/5+32}
function dewPointF(tF,rh){if(tF==null||rh==null)return null;const c=(tF-32)*5/9,a=17.62,b=243.12,g=a*c/(b+c)+Math.log(rh/100),d=b*g/(a-g);return d*9/5+32}
function cardinal(d){if(d==null)return'—';return['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'][Math.round(d/22.5)%16]}
function parseLocal(s){return new Date(`${s}:00`)}function hourKey(d=new Date()){const x=new Date(d);x.setMinutes(0,0,0);return x.toISOString()}
async function json(url,headers={}){const r=await fetch(url,{cache:'no-store',headers});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function status(ok,text){$('statusDot').classList.toggle('bad',!ok);$('statusText').textContent=text}
function showToast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function installHolidayStyles(){if(document.getElementById('holidayStyles'))return;const style=document.createElement('style');style.id='holidayStyles';style.textContent=`.holiday-stage{position:fixed;left:0;right:0;top:0;height:150px;z-index:1000;pointer-events:none;overflow:hidden}.santa-flight{position:absolute;top:22px;left:-560px;font-size:58px;white-space:nowrap;filter:drop-shadow(0 5px 6px rgba(0,0,0,.45));animation:santaAcross 16s linear forwards}.santa-message{position:absolute;top:100px;left:50%;transform:translateX(-50%);font-size:20px;font-weight:900;color:#fff;text-shadow:0 2px 8px #000;opacity:0;animation:holidayMessage 5s ease 2s}.firework{position:absolute;width:8px;height:8px;border-radius:50%;animation:fireworkBurst 1.6s ease-out forwards}.firework:before,.firework:after{content:'';position:absolute;inset:-42px;border-radius:50%;background:repeating-conic-gradient(from 0deg,currentColor 0 4deg,transparent 4deg 25deg);mask:radial-gradient(circle,transparent 0 33px,#000 34px 42px,transparent 43px);-webkit-mask:radial-gradient(circle,transparent 0 33px,#000 34px 42px,transparent 43px)}.firework:after{transform:rotate(12deg) scale(.72)}@keyframes santaAcross{to{transform:translateX(calc(100vw + 620px))}}@keyframes holidayMessage{0%,100%{opacity:0}20%,80%{opacity:1}}@keyframes fireworkBurst{0%{transform:translateY(110px) scale(.1);opacity:0}35%{opacity:1}100%{transform:translateY(0) scale(1.35);opacity:0}}@media(prefers-reduced-motion:reduce){.santa-flight,.firework{animation-duration:.01ms!important}.santa-message{animation:none;opacity:1}}`;document.head.appendChild(style)}
function holidayFor(date){const m=date.getMonth()+1,d=date.getDate();if(m===12&&d===25)return'christmas';if(m===7&&d===4)return'july4';return null}
function runChristmas(){const stage=document.createElement('div');stage.className='holiday-stage';stage.innerHTML='<div class="santa-flight">🦌 🦌 🦌 🦌 🛷🎅</div><div class="santa-message">Merry Christmas from McPherson BPU!</div>';document.body.appendChild(stage);setTimeout(()=>stage.remove(),17000)}
function runFireworks(){const stage=document.createElement('div');stage.className='holiday-stage';const colors=['#ff4d4d','#ffffff','#4d8dff','#ffd84d','#69ff91'];for(let i=0;i<18;i++){const burst=document.createElement('span');burst.className='firework';burst.style.left=`${5+Math.random()*90}%`;burst.style.top=`${18+Math.random()*72}px`;burst.style.color=colors[i%colors.length];burst.style.animationDelay=`${Math.random()*7}s`;stage.appendChild(burst)}document.body.appendChild(stage);setTimeout(()=>stage.remove(),10000)}
function checkHolidayEffect(){const now=new Date(),holiday=holidayFor(now);if(!holiday||now.getMinutes()!==0)return;const key=`bpu-holiday-${holiday}-${localDateKey(now)}-${now.getHours()}`;if(localStorage.getItem(key))return;localStorage.setItem(key,'1');installHolidayStyles();holiday==='christmas'?runChristmas():runFireworks()}
function tempClass(t){if(t>=105)return'critical';if(t>=95)return'hot';if(t<70)return'cool';return''}
function wetClass(t){if(t>=82)return'critical';if(t>=78)return'hot';return''}
function setValue(id,text,cls=''){const el=$(id);if(!el)return;el.textContent=text;el.classList.remove('cool','hot','critical');if(cls)el.classList.add(cls)}
function pressureTrend(hourly){const vals=hourly?.pressure_msl||[];const valid=vals.filter(v=>v!=null);if(valid.length<4)return'—';const now=valid.at(-1),prior=valid.at(-4),diff=(now-prior)*.029529983;if(Math.abs(diff)<.01)return'→ Steady (3 hr)';return`${diff>0?'▲ Rising':'▼ Falling'} ${Math.abs(diff).toFixed(2)} inHg / 3 hr`}
function currentTiles(c,hourly,elevation){const t=c.temperature_2m,rh=c.relative_humidity_2m,p=c.pressure_msl,w=c.wind_speed_10m,g=c.wind_gusts_10m,d=c.wind_direction_10m,wet=wetBulbF(t,rh),dew=dewPointF(t,rh),trend=pressureTrend(hourly);setValue('dryBulb',t==null?'—':`${round(t)}°F`,tempClass(t));setValue('alignedDryBulb',t==null?'—':`${round(t)}°F`,tempClass(t));setValue('wetBulb',wet==null?'—':`${round(wet)}°F`,wetClass(wet));setValue('alignedWetBulb',wet==null?'—':`${round(wet)}°F`,wetClass(wet));setValue('dewPoint',dew==null?'—':`${round(dew)}°F`);setValue('alignedDewPoint',dew==null?'—':`${round(dew)}°F`);$('humidity').textContent=rh==null?'—':`${round(rh)}%`;$('alignedHumidity').textContent=rh==null?'—':`${round(rh)}%`;$('pressure').textContent=p==null?'—':`${round(p*.029529983,2)}`;$('alignedPressure').textContent=p==null?'—':`${round(p*.029529983,2)}`;$('pressureTrend').textContent=trend;$('alignedPressureTrend').textContent=trend;$('windSpeed').textContent=w==null?'—':`${round(w)} mph`;$('alignedWindSpeed').textContent=w==null?'—':`${round(w)} mph`;$('windGust').textContent=g==null?'—':`Gust ${round(g)} mph`;$('alignedWindGust').textContent=g==null?'—':`${round(g)} mph`;$('windDirection').textContent=cardinal(d);$('alignedWindDirection').textContent=cardinal(d);$('windDegrees').textContent=d==null?'—':`${round(d)}°`;$('alignedWindDegrees').textContent=d==null?'—':`${round(d)}°`;$('windArrow').style.transform=`rotate(${d??0}deg)`;$('elevation').textContent=elevation==null?'—':`${round(elevation*3.28084)} ft`;lastUpdated=new Date();nextRefresh=new Date(lastUpdated.getTime()+REFRESH_MS);updateClock()}
function chart(id,label,data,unit){return new Chart($(id),{type:'line',data:{labels:label,datasets:[{data,borderWidth:2,tension:.25,pointRadius:0,pointHoverRadius:4}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{display:false},tooltip:{callbacks:{title:items=>items[0]?.label||'',label:item=>`${item.formattedValue}${unit}`}},zoom:{limits:{x:{min:0,max:47,minRange:23}},pan:{enabled:true,mode:'x',threshold:5}}},scales:{x:{min:24,max:47,ticks:{color:'#9eb0c9',maxTicksLimit:8},grid:{color:'rgba(255,255,255,.06)'}},y:{ticks:{color:'#9eb0c9'},grid:{color:'rgba(255,255,255,.06)'}}}}})}
function rebuild(hourly){const times=(hourly.time||[]).map(parseLocal),now=new Date();now.setMinutes(0,0,0);rows=[];for(let i=47;i>=0;i--){const target=new Date(now);target.setHours(now.getHours()-i);const idx=times.findIndex(x=>x.getTime()===target.getTime());const t=idx<0?null:hourly.temperature_2m[idx],rh=idx<0?null:hourly.relative_humidity_2m[idx];rows.push({time:target,t,rh,wet:wetBulbF(t,rh),dew:dewPointF(t,rh),p:idx<0?null:hourly.pressure_msl[idx],w:idx<0?null:hourly.wind_speed_10m[idx]})}charts.forEach(c=>c.destroy());const labels=rows.map(r=>r.time.toLocaleString([],{weekday:'short',hour:'numeric'})),temp=rows.map(r=>round(r.t,1)),humidity=rows.map(r=>round(r.rh)),pressure=rows.map(r=>r.p==null?null:round(r.p*.029529983,2)),wind=rows.map(r=>round(r.w,1));charts=[chart('tempChart',labels,temp,'°F'),chart('humidityChart',labels,humidity,'%'),chart('pressureChart',labels,pressure,' inHg'),chart('windChart',labels,wind,' mph')];frozenHour=hourKey();requestAnimationFrame(()=>charts.forEach(c=>c.resize()))}
function renderDaily(daily){if(!daily?.time?.length)return;const fmt=t=>new Date(t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),sunrise=daily.sunrise?.[0],sunset=daily.sunset?.[0];$('sunrise').textContent=sunrise?fmt(sunrise):'—';$('sunset').textContent=sunset?fmt(sunset):'—';if(sunrise&&sunset){const mins=Math.round((new Date(sunset)-new Date(sunrise))/60000);$('daylight').textContent=`${Math.floor(mins/60)}h ${mins%60}m daylight`}else $('daylight').textContent='—';const labels=daily.time.map(t=>new Date(`${t}T12:00:00`).toLocaleDateString([],{weekday:'short'})),high=daily.temperature_2m_max||[],low=daily.temperature_2m_min||[];if(forecastChart)forecastChart.destroy();forecastChart=new Chart($('forecastChart'),{type:'line',data:{labels,datasets:[{label:'High',data:high,borderWidth:2,tension:.25,pointRadius:3},{label:'Low',data:low,borderWidth:2,tension:.25,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{labels:{color:'#eef5ff'}},tooltip:{callbacks:{label:item=>`${item.dataset.label}: ${item.formattedValue}°F`}}},scales:{x:{ticks:{color:'#9eb0c9'},grid:{color:'rgba(255,255,255,.06)'}},y:{ticks:{color:'#9eb0c9',callback:v=>`${v}°`},grid:{color:'rgba(255,255,255,.06)'}}}}});renderIndicators()}
function indicator(name,detail,level='normal'){return`<div class="indicator ${level==='alert'?'alerting':level}"><strong>${name}</strong><span>${detail}</span></div>`}
function renderIndicators(){if(!lastWeather)return;const d=lastWeather.daily||{},h=lastWeather.hourly||{},high=Math.max(...(d.temperature_2m_max||[-Infinity])),gust=Math.max(...(d.wind_gusts_10m_max||[-Infinity])),alertCount=lastAlerts.length,now=Date.now(),times=h.time||[],precip=h.precipitation||[];let rain24=0;for(let i=0;i<times.length;i++){const ts=new Date(`${times[i]}:00`).getTime();if(ts<=now&&ts>now-24*60*60*1000&&precip[i]!=null)rain24+=Number(precip[i])}const heatLevel=high>=105?'alert':high>=95?'watch':'normal',windLevel=gust>=58?'alert':gust>=40?'watch':'normal',rainLevel=rain24>=3?'alert':rain24>=2?'watch':'normal',nwsLevel=alertCount?((lastAlerts.some(a=>/warning|tornado|extreme/i.test(`${a.properties?.event||''} ${a.properties?.severity||''}`)))?'alert':'watch'):'normal';const levels=[heatLevel,windLevel,rainLevel,nwsLevel];$('eventIndicators').innerHTML=[indicator('Extreme heat',`${round(high)}°F forecast high`,heatLevel),indicator('High wind',`${round(gust)} mph max gust`,windLevel),indicator('Precipitation',`${round(rain24,2)} in past 24 hours`,rainLevel),indicator('NWS alerts',alertCount?`${alertCount} active alert${alertCount===1?'':'s'}`:'No active alerts',nwsLevel)].join('');const overall=levels.includes('alert')?'alerting':levels.includes('watch')?'watch':'normal',el=$('eventOverall');el.className=`event-state ${overall}`;el.textContent=overall==='alerting'?'Alert':overall[0].toUpperCase()+overall.slice(1)}
async function weather(force=false){status(true,'Loading…');try{const d=await json(apiUrl());lastWeather=d;currentTiles(d.current||{},d.hourly||{},d.elevation);if(force||!rows.length||frozenHour!==hourKey())rebuild(d.hourly||{});renderDaily(d.daily||{});status(true,'Live')}catch(e){console.error(e);status(false,'Data unavailable')}}
function severityClass(p){const text=`${p.severity||''} ${p.event||''}`.toLowerCase();if(text.includes('extreme')||text.includes('tornado')||text.includes('warning'))return'alert-critical';if(text.includes('severe')||text.includes('watch'))return'alert-severe';return'alert-advisory'}
async function alerts(){try{const d=await json(alertUrl(),{Accept:'application/geo+json'}),f=d.features||[];lastAlerts=f;renderIndicators();if(!f.length){$('alertBanner').className='alert hidden';return}const p=f[0].properties||{},banner=$('alertBanner');banner.className=`alert ${severityClass(p)}`;$('alertTitle').textContent=p.event||'Weather Alert';$('alertText').textContent=p.headline||p.description||'';$('alertExpires').textContent=p.expires?`Expires ${new Date(p.expires).toLocaleString()}`:''}catch(e){console.warn('Alert lookup failed',e)}}
function updateClock(){if(!lastUpdated)return;const age=Math.max(0,Math.floor((Date.now()-lastUpdated)/1000)),left=Math.max(0,Math.ceil((nextRefresh-Date.now())/1000));$('updatedText').textContent=`Updated ${age<60?`${age} sec ago`:`${Math.floor(age/60)} min ago`}`;$('nextRefreshText').textContent=`Next refresh: ${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`}
function currentRows(){return rows.slice(-24)}
function renderTable(){$('rollingBody').innerHTML=currentRows().map(r=>`<tr><td>${r.time.toLocaleString()}</td><td>${r.t==null?'—':round(r.t)+'°F'}</td><td>${r.wet==null?'—':round(r.wet)+'°F'}</td><td>${r.dew==null?'—':round(r.dew)+'°F'}</td><td>${r.rh==null?'—':round(r.rh)+'%'}</td><td>${r.p==null?'—':round(r.p*.029529983,2)+' inHg'}</td><td>${r.w==null?'—':round(r.w,1)+' mph'}</td></tr>`).join('')}
function localDateKey(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}
function exportRows(){if(!lastWeather?.hourly){showToast('Weather data is not ready');return}const hourly=lastWeather.hourly,times=hourly.time||[],temps=hourly.temperature_2m||[],humidity=hourly.relative_humidity_2m||[],indexByTime=new Map(times.map((time,index)=>[time,index])),now=new Date(),currentHour=new Date(now);currentHour.setMinutes(0,0,0);const csvRows=[];for(let dayOffset=-2;dayOffset<=0;dayOffset++){const day=new Date(now);day.setDate(now.getDate()+dayOffset);day.setHours(0,0,0,0);csvRows.push([day.toLocaleDateString()]);csvRows.push(['','Wet Bulb (F)','Dry Bulb (F)','Humidity (%)']);for(let hour=0;hour<24;hour++){const stamp=new Date(day);stamp.setHours(hour);const key=`${localDateKey(stamp)}T${String(hour).padStart(2,'0')}:00`,idx=indexByTime.get(key),isFuture=stamp>currentHour,t=idx==null||isFuture?null:temps[idx],rh=idx==null||isFuture?null:humidity[idx],wet=t==null||rh==null?null:wetBulbF(t,rh);csvRows.push([`HE${String(hour+1).padStart(2,'0')}`,wet==null?'':round(wet),t==null?'':round(t),rh==null?'':round(rh)])}if(dayOffset<0)csvRows.push([])}const csv='\ufeff'+csvRows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bpu-weather-3-day-${localDateKey(now)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showToast('Three-day weather file downloaded')}
async function copyRows(){const copy=currentRows(),text=['Timestamp\tDry Bulb (F)\tWet Bulb (F)\tDew Point (F)\tHumidity (%)\tPressure (inHg)\tWind Speed (mph)',...copy.map(r=>`${r.time.toLocaleString()}\t${r.t==null?'':round(r.t)}\t${r.wet==null?'':round(r.wet)}\t${r.dew==null?'':round(r.dew)}\t${r.rh==null?'':round(r.rh)}\t${r.p==null?'':round(r.p*.029529983,2)}\t${r.w==null?'':round(r.w,1)}`)].join('\n');await navigator.clipboard.writeText(text);showToast('Copied for Excel')}
function setLayout(aligned){$('gridView').classList.toggle('hidden',aligned);$('alignedView').classList.toggle('hidden',!aligned);$('eventPanel').classList.toggle('hidden',aligned);$('operationsGrid').classList.toggle('hidden',aligned);$('chartFootnote').classList.toggle('hidden',aligned);$('layoutBtn').textContent=aligned?'Grid View':'Aligned View';$('layoutBtn').setAttribute('aria-pressed',String(aligned));localStorage.setItem('bpu-layout',aligned?'aligned':'grid');requestAnimationFrame(()=>charts.forEach(c=>c.resize()))}
$('layoutBtn').onclick=()=>setLayout(!$('gridView').classList.contains('hidden'));
$('refreshBtn').onclick=()=>Promise.all([weather(true),alerts()]);$('exportBtn').onclick=exportRows;$('rollingBtn').onclick=()=>{renderTable();$('modal').classList.remove('hidden')};$('closeBtn').onclick=()=>$('modal').classList.add('hidden');$('copyBtn').onclick=()=>copyRows().catch(()=>showToast('Clipboard access was blocked'));$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};window.addEventListener('appinstalled',()=>showToast('Dashboard installed'));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js'));
setLayout(localStorage.getItem('bpu-layout')==='aligned');Promise.all([weather(true),alerts()]);checkHolidayEffect();setInterval(checkHolidayEffect,15000);setInterval(()=>Promise.all([weather(false),alerts()]),REFRESH_MS);setInterval(()=>{updateClock();if(frozenHour!==hourKey())weather(true)},1000);